
spring:
  datasource:
    #aliyun
    #url: jdbc:mysql://${mysql_host:rm-bp1y38hbx3c2t8y1pao.mysql.rds.aliyuncs.com}:${mysql_port:3306}/${mysql_db:oasis}?characterEncoding=utf8&useSSL=false
    #username: ${mysql_username:}
    #password: ${mysql_passwd:}
    #本地
    url: jdbc:mysql://${mysql_host:localhost}:${mysql_port:3306}/${mysql_db:oasis}?characterEncoding=utf8&useSSL=false
    username: ${mysql_username:root}
    password: ${mysql_passwd:root}
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    com.weibo.oasis.dao: info
    root: ${loggingLevel:info}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 9002
